### ISSUE TITLE
Facing issue after installing material

### ISSUE THREAD

**Issue by rakeshneelarapu** [santoshyadav198613/ShoppingApplication-Edureka#1]
Hi Santosh, Can you help me on this issue

I tried to use basic mat form field in my html , imported all dependencies and added to app.module.ts file
but facing some issues as below

ERROR in C:/Users/954150/Documents/PROJECTS/ContactList/contactListApp/node_modules/@angular/material/grid-
list/typings/grid-tile.d.ts (8,10): Module '"C:/Users/954150/Documents/PROJECTS/ContactList/contactListApp/
node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/Users/954150/Documents/PROJECTS/ContactList/contactListApp/node_modules/@angular/material/grid-
list/typings/grid-list.d.ts (8,50): Module '"C:/Users/954150/Documents/PROJECTS/ContactList/contactListApp/
node_modules/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/Users/954150/Documents/PROJECTS/ContactList/contactListApp/node_modules/@angular/material/icon/
typings/icon.d.ts (1,41): Module '"C:/Users/954150/Documents/PROJECTS/ContactList/contactListApp/node_modul
es/@angular/core/index"' has no exported member 'Renderer2'.

ERROR in C:/Users/954150/Documents/PROJECTS/ContactList/contactListApp/node_modules/@angular/material/icon/
typings/icon.d.ts (38,22): Class 'MatIcon' incorrectly implements interface 'CanColor'.
  Property 'color' is missing in type 'MatIcon'.

ERROR in C:/Users/954150/Documents/PROJECTS/ContactList/contactListApp/node_modules/@angular/material/icon/
typings/icon.d.ts (38,38): Type '(new (...args: any[]) => CanColor) & typeof MatIconBase' is not a construc
tor function type.

**Comment by santoshyadavdev** [comment]
Please share your code repository.

**Comment by rakeshneelarapu** [comment]
Hi Santosh, i resolved the above issue . it was due to improper versions which was not supporting Angular Material.
